###############################################################
# Program:
#     Assignment 04 - Ecommerce Product
#     Brother Dudley, CS165
# Author:
#     Sandro Tamborindegui
# Summary:
#     Summaries are not necessary for checkpoint assignments.
# CODE REVIEW: Be careful what you send in your tar file, what you
#   sent me is colloquially known as a 'tar bomb' and has the potential
#   to cause you compilation issues (-2)
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

